---
# Run commands from API
- hosts: localhost

  vars:
    hostcmd_info:
      test_sshd_1:
        cmd: "bHMgLWx0ciAkSE9NRQo="
        #cmd: "ls -ltr $HOME"
        user_to_run: root
      test_sshd_2:
        cmd: "WyAtZCAkSE9NRSBdICYmIGVjaG8gJEhPTUUgZXhpc3RzCg=="
        #cmd: "[ -d $HOME ] && echo success"
        user_to_run: root

  tasks:

    - name: Gather subset of facts
      setup:
        gather_subset: '!all'

    - name: Add hosts to group
      add_host:
        groups: group_to_use
        hostname: "{{ item }}"
        command_to_run: "{{ hostcmd_info[item]['cmd'] }}"
        user_to_run: "{{ hostcmd_info[item]['user_to_run'] }}"
      loop: "{{ hostcmd_info.keys() | list}}"

- hosts: group_to_use
  become: yes
  become_user: ansible-test

  vars:
     command_to_run_dec64: "{{ command_to_run | b64decode | string}}"

  tasks:
    - debug:
        msg:
          - "{{ command_to_run_dec64 }}"

    - name: Command bloc
      block:

        - name: Run command for Linux
          shell: "{{ command_to_run_dec64 }}"
            #shell: "{{ command_to_run }}"
          register: linux_cmdout
          when: ansible_system == "Linux"

        - name: Run command for Windows
          shell: "{{ command_to_run_dec64 }}"
          #shell: "{{ command_to_run }}"
          register: windows_cmdout
          when: ansible_system == "Windows"

      vars:
         cmdout: "{{ linux_cmdout if ansible_system == 'Linux' else windows_cmdout }}"


      always:
        - debug:
            msg:
              - "Command run was {{ command_to_run_dec64 }}"
              - "Stdout was {{ cmdout.stdout_lines }}"
              - "Stderr was {{ cmdout.stderr_lines }}"
              - "RC was {{ cmdout.rc }}"

        - name: Set Tower WF Response
          set_fact:
            tower_wf_response: '{{ tower_wf_response | default({}) |
                                   combine(
                                     {
                                      "cmd": cmdout.cmd,
                                      "stdout": cmdout.stdout_lines,
                                      "stderr": cmdout.stderr_lines,
                                      "system": ansible_system,
                                      "ansible_host": ansible_host,
                                      "rc": cmdout.rc
                                     }
                                   )
                                }}'

        - name: Tower Response Facts
          set_fact:
            svalue: value
          with_items:
            - "{{ tower_wf_response | to_json }}"
